// Reads every committed `src/deployments/<chainId>.json`, validates each against
// the Zod `DeploymentManifest` schema (fail-fast on malformed input), and emits
// the typed `src/deployments.generated.ts` consumed at runtime — mirroring the
// trusted `export-abis` pipeline (validated, not trusted; committed, not read as
// JSON at runtime). Run via `pnpm --filter @matura/chain gen:deployments`.
import { readFileSync, writeFileSync, globSync } from "node:fs";
import { register } from "node:module";
import { fileURLToPath } from "node:url";
import { basename, dirname, join } from "node:path";

// Runtime `src/*` code uses NodeNext `.js` import specifiers that actually point
// at `.ts` sources (repo convention, required by bundler consumers). Plain `node`
// type-stripping does not remap `.js` → `.ts`, so we register a minimal resolve
// hook that does, then dynamically import the schema below (a static import would
// resolve before the hook is registered).
register(
  "data:text/javascript," +
    encodeURIComponent(
      "export async function resolve(spec, ctx, next) {" +
        "  if ((spec.startsWith('./') || spec.startsWith('../')) && spec.endsWith('.js')) {" +
        "    try { return await next(spec.slice(0, -3) + '.ts', ctx); } catch { /* fall through */ }" +
        "  }" +
        "  return next(spec, ctx);" +
        "}",
    ),
  import.meta.url,
);

const { DeploymentManifest } = await import("../src/manifest.ts");

const here = dirname(fileURLToPath(import.meta.url));
const deploymentsDir = join(here, "../src/deployments");
const outFile = join(here, "../src/deployments.generated.ts");

const files = globSync(join(deploymentsDir, "*.json")).sort();

const entries: string[] = [];
for (const file of files) {
  const raw: unknown = JSON.parse(readFileSync(file, "utf8"));
  // Throws (fails the build) on any malformed manifest — "validated, not trusted".
  const manifest = DeploymentManifest.parse(raw);
  const fileChainId = Number.parseInt(basename(file, ".json"), 10);
  if (manifest.chainId !== fileChainId) {
    throw new Error(
      `Manifest chainId ${String(manifest.chainId)} does not match file name ${basename(file)}`,
    );
  }
  entries.push(`  ${String(manifest.chainId)}: ${JSON.stringify(manifest, null, 2)},`);
}

const body =
  `// AUTO-GENERATED by packages/chain/scripts/gen-deployments.ts — do not edit by hand.\n` +
  `import type { DeploymentManifest } from "./manifest.js";\n\n` +
  `export const MANIFESTS = {\n${entries.join("\n")}\n} as const satisfies Record<number, DeploymentManifest>;\n`;

writeFileSync(outFile, body);

console.log(`Generated ${outFile} from ${String(files.length)} manifest(s).`);
