// Reads compiled Hardhat 3 artifacts and emits `as const` ABI TypeScript into
// @matura/chain/src/abis (JIT raw-TS package — ABIs are committed, not read at runtime).
// Run via `pnpm --filter @matura/contracts contracts:export-abis` (after `hardhat compile`).
import { readFileSync, writeFileSync, mkdirSync, globSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const artifactsDir = join(here, "../artifacts/contracts");
const outDir = join(here, "../../chain/src/abis");

// Only export the protocol contracts @matura/chain needs (excludes OZ bases + test mocks).
const WANTED = new Set([
  "MockUSDT",
  "IssuerRegistry",
  "ClaimRegistry",
  "LiquidityVault",
  "VaultRegistry",
  "MaturaRouter",
  "SettlementManager",
  "SourceObligor",
]);

interface HardhatArtifact {
  _format: string;
  contractName: string;
  abi: unknown[];
}

function isArtifact(value: unknown): value is HardhatArtifact {
  if (typeof value !== "object" || value === null) return false;
  const o = value as Record<string, unknown>;
  return (
    o._format === "hh3-artifact-1" && typeof o.contractName === "string" && Array.isArray(o.abi)
  );
}

mkdirSync(outDir, { recursive: true });

const files = globSync(join(artifactsDir, "**/*.json"));
const exported: string[] = [];

for (const file of files) {
  const parsed: unknown = JSON.parse(readFileSync(file, "utf8"));
  if (!isArtifact(parsed)) continue;
  if (!WANTED.has(parsed.contractName)) continue;
  const camel = parsed.contractName.charAt(0).toLowerCase() + parsed.contractName.slice(1);
  const body =
    `// AUTO-GENERATED by packages/contracts/scripts/export-abis.ts — do not edit by hand.\n` +
    `export const ${camel}Abi = ${JSON.stringify(parsed.abi, null, 2)} as const;\n`;
  writeFileSync(join(outDir, `${camel}.ts`), body);
  exported.push(camel);
}

exported.sort();
const barrel =
  `// AUTO-GENERATED by packages/contracts/scripts/export-abis.ts — do not edit by hand.\n` +
  exported.map((c) => `export { ${c}Abi } from "./${c}.js";`).join("\n") +
  "\n";
writeFileSync(join(outDir, "index.ts"), barrel);

console.log(`Exported ${exported.length} ABIs: ${exported.join(", ")}`);
