// AUTO-GENERATED by packages/chain/scripts/gen-deployments.ts — do not edit by hand.
import type { DeploymentManifest } from "./manifest.js";

export const MANIFESTS = {
  31337: {
  "chainId": 31337,
  "deploymentBlock": "0",
  "abiBuildId": "",
  "addresses": {
    "mockUsdt": "0x0000000000000000000000000000000000000000",
    "issuerRegistry": "0x0000000000000000000000000000000000000000",
    "claimRegistry": "0x0000000000000000000000000000000000000000",
    "vaultRegistry": "0x0000000000000000000000000000000000000000",
    "router": "0x0000000000000000000000000000000000000000",
    "settlementManager": "0x0000000000000000000000000000000000000000"
  },
  "namedVaults": {
    "stableVault": "0x0000000000000000000000000000000000000000",
    "flexVault": "0x0000000000000000000000000000000000000000"
  },
  "sources": {
    "payroll": "0x0000000000000000000000000000000000000000",
    "freelance": "0x0000000000000000000000000000000000000000",
    "stream": "0x0000000000000000000000000000000000000000"
  }
},
  97: {
  "chainId": 97,
  "deploymentBlock": "133632667",
  "abiBuildId": "sha256:9efbe90658807d285ab7989c7f7cf37e989185e9f875493434ed35ed44228d27",
  "addresses": {
    "mockUsdt": "0x160d49be56a24e637d4084867133650ED31c9377",
    "issuerRegistry": "0xe28bF3D985f883605F4B384b5aea54006890b97B",
    "claimRegistry": "0x4208B8336024649492D2E57493a551fC96Ed5aA4",
    "vaultRegistry": "0xF4d63f3d62c5d4D6122b6cb6C768f8d8D8daFC0e",
    "router": "0xaA685233Cf2334d53523fFaA368B36528f0cD955",
    "settlementManager": "0x74c25a326542D55434527fB3E43DF3D4a9397783"
  },
  "namedVaults": {
    "stableVault": "0x897fa1b8651f21caCd5d4D50d740aF5CA6a137c5",
    "flexVault": "0x1853E27c413621Cf73A3B4aa69521dEaA48d276F"
  },
  "sources": {
    "payroll": "0x65A476F86b3d621ecB5353c3b4c3FBa0d24F3416",
    "freelance": "0x510d2b9579025f275dD46C807e1e9Edb1b147b30",
    "stream": "0x7d6b72f9443F4C0015B41097248AC598e74F59E8"
  }
},
} as const satisfies Record<number, DeploymentManifest>;
