// AUTO-GENERATED by packages/contracts/scripts/export-demo-fixture.ts — do not edit by hand.
import type { DemoFixture } from "./demo.js";

export const DEMO_FIXTURE = {
  "chainId": 97,
  "generatedFrom": "packages/contracts/config/demo.ts",
  "claims": [
    {
      "label": "alice-payroll",
      "kind": "signed",
      "claimType": "PAYROLL",
      "faceUnits": "20000000000",
      "dueInDays": 30
    },
    {
      "label": "alice-freelance",
      "kind": "escrow",
      "claimType": "FREELANCE_ESCROW",
      "faceUnits": "15000000000",
      "dueInDays": 45
    },
    {
      "label": "alice-stream",
      "kind": "stream",
      "claimType": "STREAM",
      "faceUnits": "10000000000",
      "dueInDays": 30
    }
  ],
  "requests": [
    {
      "key": "A",
      "targetAdvanceUnits": "4800000000",
      "maxTotalFaceUnits": "6000000000",
      "eligibleClaims": [
        "alice-payroll"
      ]
    },
    {
      "key": "B",
      "targetAdvanceUnits": "24000000000",
      "maxTotalFaceUnits": "40000000000",
      "eligibleClaims": [
        "alice-payroll",
        "alice-freelance"
      ]
    }
  ],
  "vaults": [
    {
      "name": "stable",
      "supportedTypes": [
        "PAYROLL",
        "STREAM"
      ],
      "baseDiscountBps": 50,
      "durationBpsPerDay": 3,
      "maxDurationDays": 90,
      "minFaceUnits": "100000000",
      "maxFaceUnits": "50000000000",
      "liquidityCapUnits": "500000000000",
      "claimTypePremiumBps": [
        0,
        0,
        25
      ]
    },
    {
      "name": "flex",
      "supportedTypes": [
        "PAYROLL",
        "FREELANCE_ESCROW",
        "STREAM"
      ],
      "baseDiscountBps": 150,
      "durationBpsPerDay": 6,
      "maxDurationDays": 365,
      "minFaceUnits": "100000000",
      "maxFaceUnits": "200000000000",
      "liquidityCapUnits": "1000000000000",
      "claimTypePremiumBps": [
        0,
        75,
        25
      ]
    }
  ]
} as const satisfies DemoFixture;
