import { Injectable, Logger, type OnModuleDestroy, type OnModuleInit } from "@nestjs/common";

// The `prisma-client` generator emits plain TS source into `src/generated/prisma`;
// its entry file is `client.ts`, so we import `PrismaClient` from there (never
// from `@prisma/client`). The directory is git-ignored and regenerated by
// `prisma generate` (run before `nest build`).
import { PrismaClient } from "../generated/prisma/client";

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(PrismaService.name);

  async onModuleInit(): Promise<void> {
    await this.$connect();
    this.logger.log("Prisma client connected");
  }

  async onModuleDestroy(): Promise<void> {
    await this.$disconnect();
  }
}
